package web

import (
	"net/http"

	"github.com/google/uuid"
)

const requestIDHeader = "X-Request-ID"

// requestID attaches a server-generated correlation identifier to every
// response. It is intentionally generated by the service rather than trusting
// a client-supplied value, so logs and support reports cannot be spoofed.
func requestID(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		id := uuid.NewString()
		w.Header().Set(requestIDHeader, id)
		next.ServeHTTP(w, r)
	})
}
